using System;
using System.Xml.Serialization;
using static bangka.Commands.Arguments;

namespace bangka.Properties;

[XmlRoot("profile")]
public class DeploymentProfile
{
    // ── Build settings ────────────────────────────────────────────────────────
    [XmlElement("name")]
    public string Name { get; set; } = string.Empty;

    [XmlElement("version")]
    public string Version { get; set; } = string.Empty;

    [XmlElement("publishDir")]
    public string PublishDir { get; set; } = string.Empty;

    [XmlElement("entryDll")]
    public string EntryDll { get; set; } = string.Empty;

    [XmlElement("port")]
    public int Port { get; set; } = 5000;

    [XmlElement("user")]
    public string User { get; set; } = "www-data";

    [XmlElement("environment")]
    public string Environment { get; set; } = "Production";

    [XmlElement("author")]
    public string Author { get; set; } = string.Empty;

    [XmlElement("description")]
    public string Description { get; set; } = string.Empty;

    [XmlElement("envFile")]
    public string EnvFile { get; set; } = string.Empty;

    [XmlElement("outDir")]
    public string OutDir { get; set; } = ".";

    // ── Deploy settings ───────────────────────────────────────────────────────
    [XmlElement("host")]
    public string Host { get; set; } = string.Empty;

    [XmlElement("sshUser")]
    public string SshUser { get; set; } = string.Empty;

    [XmlElement("keyPath")]
    public string KeyPath { get; set; } = string.Empty;

    [XmlElement("sshPort")]
    public int SshPort { get; set; } = 22;

    // ── Cloudflare (optional) ─────────────────────────────────────────────────
    [XmlElement("cfTunnelId")]
    public string CfTunnelId { get; set; } = string.Empty;

    [XmlElement("cfTunnelName")]
    public string CfTunnelName { get; set; } = string.Empty;

    [XmlElement("cfHostname")]
    public string CfHostname { get; set; } = string.Empty;

    [XmlElement("cfCredentials")]
    public string CfCredentials { get; set; } = string.Empty;

    // ── Environment variables (stored locally, pushed to remote on deploy) ────
    [XmlArray("envVars")]
    [XmlArrayItem("var")]
    public List<ProfileEnvVar> EnvVars { get; set; } = new();

    // ── Helpers ───────────────────────────────────────────────────────────────

    public static string ProfilesDir =>
        Path.Combine(
            System.Environment.GetFolderPath(System.Environment.SpecialFolder.UserProfile),
            ".bangka", "profiles");

    public static string ProfilePath(string name) =>
        Path.Combine(ProfilesDir, $"{name}.xml");

    public static DeploymentProfile Load(string nameOrPath)
    {
        var path = File.Exists(nameOrPath)
            ? nameOrPath
            : ProfilePath(nameOrPath);

        if (!File.Exists(path))
            throw new FileNotFoundException($"Profile not found: {path}");

        var serializer = new XmlSerializer(typeof(DeploymentProfile));
        using var reader = new StreamReader(path);
        return (DeploymentProfile)serializer.Deserialize(reader)!;
    }

    public void Save(string name)
    {
        Directory.CreateDirectory(ProfilesDir);
        var serializer = new XmlSerializer(typeof(DeploymentProfile));
        using var writer = new StreamWriter(ProfilePath(name));
        serializer.Serialize(writer, this);
    }

    // ── Env var helpers ───────────────────────────────────────────────────────

    public void EnvSet(string key, string value)
    {
        var existing = EnvVars.FirstOrDefault(e => e.Key == key);
        if (existing != null)
            existing.Value = value;
        else
            EnvVars.Add(new ProfileEnvVar { Key = key, Value = value });
    }

    public bool EnvRemove(string key)
    {
        var existing = EnvVars.FirstOrDefault(e => e.Key == key);
        if (existing == null) return false;
        EnvVars.Remove(existing);
        return true;
    }

    /// <summary>
    /// Renders the env vars as a shell env file (KEY=value format).
    /// </summary>
    public string ToEnvFileContent()
    {
        var lines = new List<string>
        {
            $"# Generated by Bangka — profile: {Name}",
            $"# Last updated: {DateTime.UtcNow:O}",
            ""
        };
        lines.AddRange(EnvVars.Select(e => $"{e.Key}={e.Value}"));
        return string.Join("", lines) + "";
    }

    /// <summary>
    /// Merges profile values into BuildArgs — CLI flags (non-default values) win.
    /// </summary>
    public BuildArgs ApplyToBuildArgs(BuildArgs cli)
    {
        if (string.IsNullOrWhiteSpace(cli.Name))        cli.Name        = Name;
        if (string.IsNullOrWhiteSpace(cli.Version))     cli.Version     = Version;
        if (string.IsNullOrWhiteSpace(cli.PublishDir))  cli.PublishDir  = PublishDir;
        if (string.IsNullOrWhiteSpace(cli.EntryDll))    cli.EntryDll    = string.IsNullOrWhiteSpace(EntryDll) ? null : EntryDll;
        if (cli.Port == 5000 && Port != 5000)           cli.Port        = Port;
        if (cli.User == "www-data")                     cli.User        = User;
        if (cli.Environment == "Production")            cli.Environment = Environment;
        if (string.IsNullOrWhiteSpace(cli.Author))      cli.Author      = Author;
        if (string.IsNullOrWhiteSpace(cli.Description)) cli.Description = Description;
        if (string.IsNullOrWhiteSpace(cli.EnvFile))     cli.EnvFile     = string.IsNullOrWhiteSpace(EnvFile) ? null : EnvFile;
        if (cli.OutDir == ".")                          cli.OutDir      = OutDir;

        // Cloudflare
        if (string.IsNullOrWhiteSpace(cli.CfTunnelId))    cli.CfTunnelId    = string.IsNullOrWhiteSpace(CfTunnelId)    ? null : CfTunnelId;
        if (string.IsNullOrWhiteSpace(cli.CfTunnelName))  cli.CfTunnelName  = string.IsNullOrWhiteSpace(CfTunnelName)  ? null : CfTunnelName;
        if (string.IsNullOrWhiteSpace(cli.CfHostname))    cli.CfHostname    = string.IsNullOrWhiteSpace(CfHostname)    ? null : CfHostname;
        if (string.IsNullOrWhiteSpace(cli.CfCredentials)) cli.CfCredentials = string.IsNullOrWhiteSpace(CfCredentials) ? null : CfCredentials;

        return cli;
    }

    /// <summary>
    /// Merges profile values into DeployArgs — CLI flags win.
    /// </summary>
    public DeployArgs ApplyToDeployArgs(DeployArgs cli)
    {
        if (string.IsNullOrWhiteSpace(cli.Host))    cli.Host    = Host;
        if (string.IsNullOrWhiteSpace(cli.SshUser)) cli.SshUser = SshUser;
        if (string.IsNullOrWhiteSpace(cli.KeyPath)) cli.KeyPath = KeyPath;
        if (cli.SshPort == 22 && SshPort != 22)     cli.SshPort = SshPort;
        return cli;
    }
}
